pipeline {
    agent any

  stages {

     stage("Initial cleanup") {
          steps {
            dir("${WORKSPACE}") {
              deleteDir()
            }
          }
        }

    stage('Checkout SCM') {
      steps {
            git branch: 'main', url: 'https://github.com/UmarFaruqk/php-todo'
      }
    }

    stage('Prepare Dependencies') {
      steps { 
              sh 'echo pass'
             //sh 'mv  .env.sample .env'
             //sh 'composer install'
             //sh 'php artisan migrate'
             //sh 'php artisan db:seed'
             //sh  'php artisan key:generate'
      }
    }
  }
}
