pipeline {
    agent any
        environment {ANSIBLE_CONFIG = "${WORKSPACE}/deploy/ansible.cfg" }
    stages {
        stage("Checkout SCM") {
            steps {
                git branch: 'main', url: 'https://github.com/UmarFaruqk/Ansible-Config-Mgt'
            }
        }
        stage("Prepare Ansible For Execution") {
            steps {
                sh 'echo ${WORKSPACE}'
                sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg'
            }
        }
 stage('Test SSH Connection') {
      steps {
        sshagent(['private-key']) {
          sh 'ssh -o StrictHostKeyChecking=no -i /home/ubuntu/Downloads/web-server2.pem ec2-user@172.31.35.170 exit'
        }
      }
    }
        stage("Run Ansible playbook") {
            steps {
                ansiblePlaybook become: true, colorized: true, disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/dev.ini', playbook: 'playbooks/site.yml'
            }
        }
        stage("Clean Workspace after build") {
            steps {
                cleanWs()
            }
        }
    }
}

