---
#- import_playbook: ../static-assignments/common.yml
- import_playbook: ../dynamic-assignments/env-vars.yml

- import_playbook: ../static-assignments/hat-webservers/hat-webservers.yml

- import_playbook: ../static-assignments/loadbalancer.yml
  when: load_balancer_is_required

